import {create} from 'zustand';

const useStore = create((set) => ({
  distance: null,
  duration: null,
  addCard:false,
  addLocation:'',
  price:'',
  paymentMethod:'Cash',
  apply:'false',
  exit:'false',
  repeatRoute:'false',
  repeatData:{
    id:'',
    UserId:'',
    StartLocation:'',
    EndLocation:'',
    RoadLength:'',
    Price:'',
  },
  serviceData:[],
  editStatus:'false',
  justEdit:'false',
  refresh:'',
  refreshPayment:'',
  render:'true',
  setDistance: (distance) => set({ distance }),
  setDuration: (duration) => set({ duration }),
  setAddCard: (addCard) => set({addCard}),
  setLocation :(addLocation) => set ({addLocation}),
  setPrice:(price)=>set({price}),
  setPaymentMethod:(paymentMethod)=>set({paymentMethod}),
  setApply:(apply)=>set({apply}),
  setExit:(exit)=>set({exit}),
  setRepeatRoute:(repeatRoute)=>set({repeatRoute}),
  setRepeatData:(repeatData)=>set({repeatData}),
  setServiceData:(serviceData)=>set({serviceData}),
  setEditStatus:(editStatus)=>set({editStatus}),
  setJustEdit:(justEdit)=>set({justEdit}),
  setRefresh:(refresh)=>set({refresh}),
  setRefreshPayment:(refreshPayment)=>set({refreshPayment}),
  setRender:(render)=>set({render}),
}));

export default useStore;